### ISSUE TITLE
Delete habit, edit habit, and add habit does not save changes

### ISSUE THREAD

**Issue by mbengert** [CMPUT301F21T43/CMPUT-301-Project#55]
When you press the confirm button when editing or adding a habit, instead of returning to the habit view activity it returns to  the main activity, which is just a blank page and the nav bar. When you go back to the view habit activity, you will see the change has not saved. You can delete habits as much as you want but they will be restored when you use the nav bar.

**Comment by marty-rudolf** [comment]
This seems to be the same as #53. I believe this to be an issue involving the integration of Firebase authentication, but I'm not sure why. It could involve the dialog that prompts for username on the first time you sign in, which might explain why the .xml is not being properly rendered (since the add button and list items would be assumed to be in a background layer with the dialog on top).

**Comment by marty-rudolf** [comment]
This problem was caused by having Firebase write rules not working. Reverted to firebase `allow write if true;`.
